Models/Image.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int MemberId { get; set; }
        public string MemberName { get; set; }
        public string PhoneNumber { get; set; }
        public string ImagePath { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> IsModified { get; set; }
        public string ModifiedName { get; set; }
    }
}

Models/Member.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Gallery.Models
{
    public class Member
    {
        [DisplayName("Member Name")]
        public string Name { get; set; }

        public int MemberId { get; set; }

        //To change label title value  
        [DisplayName("Telephone / Mobile Number")]
        public string PhoneNumber { get; set; }

        //To change label title value  
        [DisplayName("Upload File")]
        public string ImagePath { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public string ImageName { get; set; }

        public Nullable<bool> IsModified { get; set; }

        public string ModifiedName { get; set; }
    }
}

Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
        
    public partial class MEntities : DbContext
    {
        public MEntities()
            : base("name=MEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Images { get; set; }
    }
}

Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Manoj A H\source\repos\Gallery\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Controllers/userController.cs
using Gallery.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gallery.Controllers
{
    public class userController : Controller
    {
        // GET: user

        public ActionResult Index()
        {
            return View();
        }

       [HttpPost]
        public ActionResult Index(HttpPostedFileBase ImageFile,Member member)
        {
            MEntities mEntities = new MEntities();

            string FileName = Path.GetFileName(ImageFile.FileName);

            //To Get File Extension  
            string FileExtension = "~/Gallery/"+FileName;

            ImageFile.SaveAs(Server.MapPath(FileExtension));

            Image image = new Image();
            var a = member.Name;
            var b = member.PhoneNumber;
            var c = FileExtension;
            var d = FileName;

            image.MemberName = a;
            image.PhoneNumber = b;
            image.ImagePath = c;
            image.ImageName = d;
            mEntities.Images.Add(image);
            mEntities.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GetData( )

        {
            MEntities entities = new MEntities();
            var v = entities.Images.ToList();
            return View(v);
        }


        public ActionResult Edit(int Id)
        {
            //here, get the student from the database in the real application
            MEntities entities = new MEntities();

            //getting a student from collection for demo purpose
            var std = entities.Images.Where(s => s.MemberId == Id).FirstOrDefault();

            return View(std);
        }
        [HttpPost]
        public  ActionResult Edit(Image image)
        {
            MEntities entities = new MEntities();

            if (image.ModifiedName!=null)
            {
                image.IsModified = true;

                entities.Entry(image).State = System.Data.Entity.EntityState.Modified;
                entities.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Views/user/Edit.cshtml
@model  Gallery.Models.Image
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "user", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MemberName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MemberName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MemberName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.HiddenFor(model => model.ImagePath)
        @Html.HiddenFor(model => model.MemberId)</div>
   
    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ModifiedName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ModifiedName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ModifiedName, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>

}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

Views/user/GetData.cshtml
@model IEnumerable< Gallery.Models.Image>
   
@{
    ViewBag.Title = "GetData";
}

<h2>GetData</h2>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>

<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
<style>  
    /* CSS for table and input (textbox) */  
    table, td, th {  
        border: 1px solid black;  
    }  
  
    

    table, tr {  
        border-collapse: collapse;  
    }  
  
    input[type=text] {  
        width: 100%;  
    }  
  
    th {  
        height: 50px;  
        text-align: center;  
    }  
</style>  
<table style="background-color:chocolate" >
    <thead>
        <tr style="width:200px" >
            <th style="width:200px">
                Member Name
            </th>
            <th style="width:200px">
                Mobile Number
            </th>
            <th style="width:200px">
                Image Name
            </th>
            <th  style="width:200px">
                Image
            </th>
            <th style="width:200px">
                Edit
            </th>
        </tr>

    </thead>
    <tbody>

       
            @foreach (var item in Model)
            {
                //for ID purpose writing this code
              
                <tr class="">
                    <td style="text-align:center">
                       @item.MemberName
                    </td>
                    <td style="text-align:center">
                        @item.PhoneNumber
                    </td>
                    <td style="text-align:center">
                        @item.ImageName" 
                    </td>                   
                    <td><img src="@Url.Content(item.ImagePath) " style="height:200px" /> </td>

                    <td> <a href="/user/Edit/@item.MemberId"> Edit</a></td>
                </tr>
            }
    </tbody>
</table>

Views/user/Index.cshtml
@model Gallery.Models.Member
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "user", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>  
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

}

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>